---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: weird-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    repos:
      copr:
        - lionheartp/Hyprland
        - atim/starship 
    install:
      packages:
        - hyprland
        - neovim
        - starship
        - xdg-desktop-portal-hyprland

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          
      - scope: user

  - type: signing
